package com.example.radioarealocator.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors (mapped to Miuix color slots)
// 默认主题色 #3482FF，配套容器/前景色按 Material 色板规范推导
val light_primary = Color(0xFF3482FF)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFD6E4FF)
val light_onPrimaryContainer = Color(0xFF001A41)
val light_secondary = Color(0xFF555F71)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFD9E3F8)
val light_onSecondaryContainer = Color(0xFF121C2B)
val light_tertiary = Color(0xFF6F5675)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFFAD8FB)
val light_onTertiaryContainer = Color(0xFF28132E)
val light_error = Color(0xFFBA1A1A)
val light_onError = Color(0xFFFFFFFF)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onErrorContainer = Color(0xFF410002)
val light_surface = Color(0xFFF5F5F5)
val light_onSurface = Color(0xFF1A1C19)
val light_surfaceVariant = Color(0xFFDDE5DA)
val light_onSurfaceVariant = Color(0xFF414941)
val light_outline = Color(0xFF717971)
val light_background = Color(0xFFF5F5F5)
val light_onBackground = Color(0xFF1A1C19)

// Dark theme colors
// 深色主题下 primary 使用 #3482FF 的提亮变体，保证暗背景上的可读性
val dark_primary = Color(0xFFADC6FF)
val dark_onPrimary = Color(0xFF002E69)
val dark_primaryContainer = Color(0xFF004294)
val dark_onPrimaryContainer = Color(0xFFD6E4FF)
val dark_secondary = Color(0xFFBDC7DC)
val dark_onSecondary = Color(0xFF273141)
val dark_secondaryContainer = Color(0xFF3D4758)
val dark_onSecondaryContainer = Color(0xFFD9E3F8)
val dark_tertiary = Color(0xFFE0BBE3)
val dark_onTertiary = Color(0xFF402843)
val dark_tertiaryContainer = Color(0xFF583E5A)
val dark_onTertiaryContainer = Color(0xFFFAD8FB)
val dark_error = Color(0xFFFFB4AB)
val dark_onError = Color(0xFF690005)
val dark_errorContainer = Color(0xFF93000A)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_surface = Color(0xFF1E1E1E)
val dark_onSurface = Color(0xFFE2E3DE)
val dark_surfaceVariant = Color(0xFF414941)
val dark_onSurfaceVariant = Color(0xFFC1C9BF)
val dark_outline = Color(0xFF8B938A)
val dark_background = Color(0xFF1E1E1E)
val dark_onBackground = Color(0xFFE2E3DE)
