package com.example.radioarealocator.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors (mapped to Miuix color slots)
val light_primary = Color(0xFF006E2C)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFF6BFF92)
val light_onPrimaryContainer = Color(0xFF002108)
val light_secondary = Color(0xFF4A6350)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFCDE9D4)
val light_onSecondaryContainer = Color(0xFF072012)
val light_tertiary = Color(0xFF3B6470)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFBFE9F8)
val light_onTertiaryContainer = Color(0xFF001F27)
val light_error = Color(0xFFBA1A1A)
val light_onError = Color(0xFFFFFFFF)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onErrorContainer = Color(0xFF410002)
val light_surface = Color(0xFFF5F5F5)
val light_onSurface = Color(0xFF1A1C19)
val light_surfaceVariant = Color(0xFFDDE5DA)
val light_onSurfaceVariant = Color(0xFF414941)
val light_outline = Color(0xFF717971)
val light_background = Color(0xFFF5F5F5)
val light_onBackground = Color(0xFF1A1C19)

// Dark theme colors
val dark_primary = Color(0xFF36D167)
val dark_onPrimary = Color(0xFF003913)
val dark_primaryContainer = Color(0xFF00531F)
val dark_onPrimaryContainer = Color(0xFFB9F6CA)
val dark_secondary = Color(0xFFB2CCB8)
val dark_onSecondary = Color(0xFF1D3526)
val dark_secondaryContainer = Color(0xFF344B3B)
val dark_onSecondaryContainer = Color(0xFFCDE9D4)
val dark_tertiary = Color(0xFFA3CDDA)
val dark_onTertiary = Color(0xFF033541)
val dark_tertiaryContainer = Color(0xFF224C57)
val dark_onTertiaryContainer = Color(0xFFBFE9F8)
val dark_error = Color(0xFFFFB4AB)
val dark_onError = Color(0xFF690005)
val dark_errorContainer = Color(0xFF93000A)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_surface = Color(0xFF1E1E1E)
val dark_onSurface = Color(0xFFE2E3DE)
val dark_surfaceVariant = Color(0xFF414941)
val dark_onSurfaceVariant = Color(0xFFC1C9BF)
val dark_outline = Color(0xFF8B938A)
val dark_background = Color(0xFF1E1E1E)
val dark_onBackground = Color(0xFFE2E3DE)
